apiVersion: v1
kind: Service
metadata:
  name: k8s-microservice
  labels:
    app: k8s-microservice
spec:
  type: NodePort
  selector:
    app: k8s-microservice
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080  # Access via minikube IP:30080
